debug: true #启动调试日志

spring:
  application:
    name: apilog
  banner:
    charset: UTF-8
    location: classpath:Banner/Big.txt
    image:
      height: 5
      invert: true
  datasource:
    url: jdbc:mysql://118.31.8.19:3306/mine_local?characterEncoding=UTF-8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true #开启热部署
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 118.31.8.19
    port: 6379
    timeout: 3000 # 连接超时时间 单位 ms（毫秒）
    #=========redis线程池设置=========
    jedis:
      pool:
        max-active: 2000 # 如果赋值为-1，则表示不限制；pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        min-idle: 10 #连接池中的最小空闲连接，默认值也是0
        max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
        max-idle: 40 # 连接池中的最大空闲连接，默认值也是8。

server:
  port: 8090


logging:
  level:
    # 禁止一些无用的日志输出
    org.springframework.boot.autoconfigure: ERROR