debug: true #启动调试日志

spring:
  application:
    name: apilog
  banner:
    charset: UTF-8
    location: classpath:Banner/Big.txt
    image:
      height: 5
      invert: true
  datasource:
    url: jdbc:mysql://118.31.8.19:3306/mine_local?characterEncoding=UTF-8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true #开启热部署
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 118.31.8.19
    port: 6379
    timeout: 3000
    pool:
      max-idle: 8
      min-idle: 200
      max-active: 2000
      max-wait: 1000
server:
  port: 8090
