debug: true #启动调试日志

spring:
  application:
    name: apilog
  banner:
    charset: UTF-8
    location: classpath:Banner/Big.txt
    image:
      height: 5
      invert: true
  datasource:
    url: jdbc:mysql://localhost:3306/mine_local?characterEncoding=UTF-8
    username: root
    password: 1234567